### ISSUE TITLE
Vamos tentar automatizar essas atualizações

### ISSUE THREAD

**Issue by lubianat** [jvfe/wdt_contribs#1]
Fala, João, beleza??

Massa o trabalho aqui!
Se quiser, eu topo trabalhar junto para tentar automatizar algumas dessas coisas, para atualizar automaticamente.

O quickstatements em teoria suporta controle via API (https://www.wikidata.org/wiki/Help:QuickStatements#Using_the_API_to_start_batches) mas nunca usei. 

Podemos criar um repositório novo também e organizar bonitinho, para servir de suporte para códigos para o wikiprojeto da Covid-19. Posso criar no meu github, e fico responsável por monitorar issues e organizar a estrutura de repositórios e tal. Ou pode ser aí no seu. O que acha?

Valeu, abraço!

**Comment by jvfe** [comment]
Po acho uma boa ideia, já tava pensando de fazer algo assim mesmo. Não entendi direito como funciona o suporte a API do QS mas podemos tentar incorporar também kkkkk. 

Cria um repositório na tua conta e me adiciona como contribuidor que eu ajudo no que puder.

**Comment by jvfe** [comment]
Só atualizando que eu to com uma boa parte de automatização já, tenho um script selenium pra baixar do site do Min da saúde o csv mais recente e outro script pra tratar o dado e gerar o QS. 

Precisa de diversas melhorias, pq no momento o QS ta indo pra stdout, então acho que uma melhor integração dos dois scripts e da API do QS que você falou melhoraria bastante. 

Assim que você criar o repositório coloco esses dois scripts lá pra tu dar uma olhada e ver se consegue melhorar.
